# Generated by Django 3.1.7 on 2021-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(null=True)),
                ('byline', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('abstract', models.TextField()),
                ('is_draft', models.BooleanField()),
            ],
        ),
    ]
