# Generated by Django 3.1.13 on 2022-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
