# Generated by Django 3.1.13 on 2022-01-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='pub_date',
        ),
    ]
