# Generated by Django 3.1.13 on 2022-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_blogentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
