# Generated by Django 3.1.13 on 2022-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220104_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
